prod:
  twilio:
      account_sid: 'AC3d433258fe9b280b01ba83afe272f438'
      auth_token: '2cc106ae7b360c99a7be11cc4ea77c07'
      phone_number: '+18337034125'
  openai:
    api_key: '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'
  firebase:
    calls_db: 'prod_calls'
    pharmacy_db: 'prod_pharmacies'
    search_requests_db: 'prop_search_requests'
    pending_search_requests_db: 'prod_pending_search_requests'
    users_db: 'prod_users'
  cloud_functions:
    get_pharmacies: 'https://us-central1-rxradar.cloudfunctions.net/prod-get-pharmacies'
    create_call: 'https://us-central1-rxradar.cloudfunctions.net/prod-create-call-twilio-bland'
dev:
  twilio:
      account_sid: 'AC3d433258fe9b280b01ba83afe272f438'
      auth_token: '2cc106ae7b360c99a7be11cc4ea77c07'
      phone_number: '+18337034125'
  openai:
    api_key: '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'
  firebase:
    calls_db: 'dev_calls'
    pharmacy_db: 'dev_pharmacies'
    search_requests_db: 'dev_search_requests'
    pending_search_requests_db: 'dev_pending_search_requests'
    users_db: 'dev_users'
  cloud_functions:
    get_pharmacies: 'https://us-central1-rxradar.cloudfunctions.net/dev-get-pharmacies'
    create_call: 'https://us-central1-rxradar.cloudfunctions.net/dev-create-call-twilio-bland'
